#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v13
# autospec commit: dc0ff31
#
Name     : fwupd-efi
Version  : 1.6
Release  : 5
URL      : https://github.com/fwupd/fwupd-efi/archive/1.6/fwupd-efi-1.6.tar.gz
Source0  : https://github.com/fwupd/fwupd-efi/archive/1.6/fwupd-efi-1.6.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: fwupd-efi-libexec = %{version}-%{release}
Requires: fwupd-efi-license = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : gnu-efi-dev
BuildRequires : gnu-efi-staticdev
BuildRequires : pypi(pefile)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# EFI executable for fwupd
[![OpenSSF Scorecard](https://api.securityscorecards.dev/projects/github.com/fwupd/fwupd-efi/badge)](https://securityscorecards.dev/viewer/?uri=github.com/fwupd/fwupd-efi)

%package dev
Summary: dev components for the fwupd-efi package.
Group: Development
Provides: fwupd-efi-devel = %{version}-%{release}
Requires: fwupd-efi = %{version}-%{release}

%description dev
dev components for the fwupd-efi package.


%package libexec
Summary: libexec components for the fwupd-efi package.
Group: Default
Requires: fwupd-efi-license = %{version}-%{release}

%description libexec
libexec components for the fwupd-efi package.


%package license
Summary: license components for the fwupd-efi package.
Group: Default

%description license
license components for the fwupd-efi package.


%prep
%setup -q -n fwupd-efi-1.6
cd %{_builddir}/fwupd-efi-1.6
pushd ..
cp -a fwupd-efi-1.6 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1719963541
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir
GOAMD64=v3
CFLAGS="$CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -march=x86-64-v3 " meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddiravx2
ninja -v -C builddiravx2

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/fwupd-efi
cp %{_builddir}/fwupd-efi-%{version}/COPYING %{buildroot}/usr/share/package-licenses/fwupd-efi/01a6b4bf79aca9b556822601186afab86e8c4fbf || :
cp %{_builddir}/fwupd-efi-%{version}/contrib/debian/copyright %{buildroot}/usr/share/package-licenses/fwupd-efi/025d2aafdf57cdf11ed493d11d40ab0a4901a20f || :
cp %{_builddir}/fwupd-efi-%{version}/contrib/debian/signing-template/copyright %{buildroot}/usr/share/package-licenses/fwupd-efi/c1a12b921301c21ba9b3dc26e7db1d859bb8259d || :
GOAMD64=v3
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/lib64/pkgconfig/fwupd-efi.pc

%files libexec
%defattr(-,root,root,-)
/usr/libexec/fwupd/efi/fwupdx64.efi

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/fwupd-efi/01a6b4bf79aca9b556822601186afab86e8c4fbf
/usr/share/package-licenses/fwupd-efi/025d2aafdf57cdf11ed493d11d40ab0a4901a20f
/usr/share/package-licenses/fwupd-efi/c1a12b921301c21ba9b3dc26e7db1d859bb8259d
